spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  boot:
    admin:
      client:
        url: http://localhost:1111/   
server:
  port: 7074
  
management:
  endpoints:
    web:
      exposure:
        include: '*'

images-upload-dir: E:\classes\product-images\
