server:
  port: 7075
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true    
  mail:
    host: smtp.gmail.com
    port: 587
    username: ashokit.classes@gmail.com
    password: lrbx nxoh fxqe tfhi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
kafka:
  topic:
    name: ashokit-orders
  bootstrap:
    url: localhost:9092
