server:
  port: 7075
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ashokit_ecomm
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true    
  mail:
    host: smtp.gmail.com
    port: 587
    username: ashokit.classes@gmail.com
    password: jdua rxfs btqb gmky
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
doubletick:
  api:
    key: key_uxchFwg4ziTdl7I9EcCFLeadAUqenGlJuedoWad9Z4qCTA9eiWTmyZRq0OKtMnys3hquGwnK7AC6A15XafrHYb5hzRHwRX4srSBQADGntxAQPL5BOggKReTwozHdVf4TAYZyDRR2C4F
    url: https://public.doubletick.io/whatsapp/message/template
kafka:
  topic:
    name: ashokit-orders
  bootstrap:
    url: localhost:9092
